### ISSUE TITLE
Error: Cannot find module 'koa'

### ISSUE THREAD

**Issue by webstermobile** [moonou/api-proxy-server#1]
cnpm install
然后node index.js报错
$ node index.js
module.js:442
    throw err;
    ^

Error: Cannot find module 'koa'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\proxy\index.js:2:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by moonou** [comment]
这个问题你检查下koa模块是否被正常安装，检查下项目目录下的node_modules目录是否有koa，如果不行可以让node_modules删除，重新运行cnpm install
